"""multi tenancy: users, members, crm_contacts, channels, knowledge

Hand-written rather than left as autogenerated. Autogenerate saw `contacts`
disappear and `crm_contacts` appear and proposed DROP + CREATE, which would
discard every existing lead and their conversations. This renames the table
instead, then backfills the new NOT NULL tenancy columns from the data already
there.

Revision ID: 3487619fe8b0
Revises: 6e8711ec3522
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3487619fe8b0"
down_revision: Union[str, None] = "6e8711ec3522"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---------------------------------------------------------------- orgs
    op.add_column(
        "organizations",
        sa.Column(
            "default_currency",
            sa.String(length=3),
            nullable=False,
            server_default="USD",
        ),
    )
    op.add_column(
        "organizations",
        sa.Column(
            "default_language",
            sa.String(length=12),
            nullable=False,
            server_default="en",
        ),
    )

    # --------------------------------------------------------------- users
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("active_organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["active_organization_id"], ["organizations.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # One unique index rather than a separate constraint plus a plain index.
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "organization_members",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role", sa.String(length=20), server_default="AGENT", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "user_id", name="uq_member_org_user"),
    )
    op.create_index(
        "ix_organization_members_organization_id", "organization_members", ["organization_id"]
    )
    op.create_index("ix_organization_members_user_id", "organization_members", ["user_id"])

    # ------------------------------------------------------------ channels
    op.create_table(
        "channel_configs",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("channel", sa.String(length=30), server_default="whatsapp", nullable=False),
        sa.Column("provider", sa.String(length=30), server_default="twilio", nullable=False),
        sa.Column("phone_number", sa.String(length=50), nullable=False),
        sa.Column("account_sid", sa.String(length=64), nullable=True),
        sa.Column("auth_token", sa.String(length=128), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel", "phone_number", name="uq_channel_number"),
    )
    op.create_index(
        "ix_channel_configs_organization_id", "channel_configs", ["organization_id"]
    )
    op.create_index("ix_channel_configs_phone_number", "channel_configs", ["phone_number"])

    # ----------------------------------------------------------- knowledge
    op.create_table(
        "knowledge_documents",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column("embedding", sa.JSON(), nullable=True),
        sa.Column("embedding_model", sa.String(length=80), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_knowledge_documents_organization_id", "knowledge_documents", ["organization_id"]
    )

    # ------------------------------------------ contacts -> crm_contacts
    # Rename, never drop: these rows are live leads.
    op.drop_index("ix_contacts_organization_id", table_name="contacts")
    op.drop_index("ix_contacts_phone_number", table_name="contacts")
    op.rename_table("contacts", "crm_contacts")

    op.add_column("crm_contacts", sa.Column("email", sa.String(length=320), nullable=True))
    op.add_column("crm_contacts", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column(
        "crm_contacts",
        sa.Column("tags", sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")),
    )

    # A lead with no organization cannot be isolated, so orphans are adopted by
    # the oldest organization before the column is tightened.
    op.execute(
        """
        UPDATE crm_contacts
           SET organization_id = (SELECT id FROM organizations ORDER BY created_at LIMIT 1)
         WHERE organization_id IS NULL
        """
    )
    op.execute("DELETE FROM crm_contacts WHERE organization_id IS NULL")
    op.alter_column("crm_contacts", "organization_id", nullable=False)
    # The default existed only to backfill existing rows; the app always
    # supplies a list, so it is dropped to keep the model and schema identical.
    op.alter_column("crm_contacts", "tags", server_default=None)

    op.create_index("ix_crm_contacts_organization_id", "crm_contacts", ["organization_id"])
    op.create_index("ix_crm_contacts_phone_number", "crm_contacts", ["phone_number"])
    # Phone numbers are unique per organization, not globally: the same person
    # may be a customer of two businesses on the platform.
    op.create_unique_constraint(
        "uq_contact_org_phone", "crm_contacts", ["organization_id", "phone_number"]
    )

    # ------------------------------------------------------------ messages
    op.add_column(
        "messages", sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.execute(
        """
        UPDATE messages
           SET organization_id = c.organization_id
          FROM crm_contacts c
         WHERE c.id = messages.contact_id
        """
    )
    op.execute("DELETE FROM messages WHERE organization_id IS NULL")
    op.alter_column("messages", "organization_id", nullable=False)
    op.create_index("ix_messages_organization_id", "messages", ["organization_id"])
    op.create_foreign_key(
        "fk_messages_organization",
        "messages",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column("messages", "contact_id", nullable=False)

    # ------------------------------------------------------------ llm_logs
    op.add_column(
        "llm_logs", sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.execute(
        """
        UPDATE llm_logs
           SET organization_id = m.organization_id
          FROM messages m
         WHERE m.id = llm_logs.message_id
        """
    )
    op.create_index("ix_llm_logs_organization_id", "llm_logs", ["organization_id"])
    op.create_foreign_key(
        "fk_llm_logs_organization",
        "llm_logs",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    op.drop_constraint("fk_llm_logs_organization", "llm_logs", type_="foreignkey")
    op.drop_index("ix_llm_logs_organization_id", table_name="llm_logs")
    op.drop_column("llm_logs", "organization_id")

    op.drop_constraint("fk_messages_organization", "messages", type_="foreignkey")
    op.drop_index("ix_messages_organization_id", table_name="messages")
    op.drop_column("messages", "organization_id")

    op.drop_constraint("uq_contact_org_phone", "crm_contacts", type_="unique")
    op.drop_index("ix_crm_contacts_phone_number", table_name="crm_contacts")
    op.drop_index("ix_crm_contacts_organization_id", table_name="crm_contacts")
    op.drop_column("crm_contacts", "tags")
    op.drop_column("crm_contacts", "notes")
    op.drop_column("crm_contacts", "email")
    op.alter_column("crm_contacts", "organization_id", nullable=True)
    op.rename_table("crm_contacts", "contacts")
    op.create_index("ix_contacts_phone_number", "contacts", ["phone_number"], unique=True)
    op.create_index("ix_contacts_organization_id", "contacts", ["organization_id"])

    op.drop_index("ix_knowledge_documents_organization_id", table_name="knowledge_documents")
    op.drop_table("knowledge_documents")

    op.drop_index("ix_channel_configs_phone_number", table_name="channel_configs")
    op.drop_index("ix_channel_configs_organization_id", table_name="channel_configs")
    op.drop_table("channel_configs")

    op.drop_index("ix_organization_members_user_id", table_name="organization_members")
    op.drop_index(
        "ix_organization_members_organization_id", table_name="organization_members"
    )
    op.drop_table("organization_members")

    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")

    op.drop_column("organizations", "default_language")
    op.drop_column("organizations", "default_currency")
