"""sales state, structured memory, product media, primary domain

Revision ID: 5ef73b9fe187
Revises: 3487619fe8b0
Create Date: 2026-09-09 22:34:51.115237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef73b9fe187'
down_revision: Union[str, None] = '3487619fe8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "crm_contacts",
        sa.Column("sales_stage", sa.String(length=30), server_default="NEW", nullable=False),
    )
    op.add_column("crm_contacts", sa.Column("last_intent", sa.String(length=120), nullable=True))
    op.add_column("crm_contacts", sa.Column("next_action", sa.String(length=120), nullable=True))
    op.add_column("organizations", sa.Column("primary_domain", sa.String(length=255), nullable=True))
    op.add_column(
        "knowledge_documents",
        sa.Column("doc_type", sa.String(length=30), server_default="policy", nullable=False),
    )

    # These are NOT NULL, so existing rows need a value before the constraint
    # can hold. The default is temporary: the application always supplies one,
    # and leaving it in place would show up as schema drift against the model.
    json_backfills = [
        ("crm_contacts", "memory", "'{}'::json"),
        ("knowledge_documents", "media_urls", "'[]'::json"),
        ("knowledge_documents", "attributes", "'{}'::json"),
        ("messages", "media_urls", "'[]'::json"),
    ]
    for table, column, default in json_backfills:
        op.add_column(
            table,
            sa.Column(column, sa.JSON(), nullable=False, server_default=sa.text(default)),
        )
        op.alter_column(table, column, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'primary_domain')
    op.drop_column('messages', 'media_urls')
    op.drop_column('knowledge_documents', 'attributes')
    op.drop_column('knowledge_documents', 'media_urls')
    op.drop_column('knowledge_documents', 'doc_type')
    op.drop_column('crm_contacts', 'memory')
    op.drop_column('crm_contacts', 'next_action')
    op.drop_column('crm_contacts', 'last_intent')
    op.drop_column('crm_contacts', 'sales_stage')
    # ### end Alembic commands ###
