"""contact metadata for vision analysis and followups

Revision ID: 634c85aa3faa
Revises: 5ef73b9fe187
Create Date: 2026-09-10 05:17:47.530224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634c85aa3faa'
down_revision: Union[str, None] = '5ef73b9fe187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT NULL, so existing rows need a value before the constraint can hold.
    # The default is temporary — the application always supplies one, and
    # leaving it would show up as drift against the model.
    op.add_column(
        "crm_contacts",
        sa.Column("metadata", sa.JSON(), nullable=False, server_default=sa.text("'{}'::json")),
    )
    op.alter_column("crm_contacts", "metadata", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crm_contacts', 'metadata')
    # ### end Alembic commands ###
