"""customer memory fields on contacts

Revision ID: 6c08ef398d26
Revises: 21231238eb98
Create Date: 2026-09-09 03:28:41.436562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c08ef398d26'
down_revision: Union[str, None] = '21231238eb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('contacts', sa.Column('shoe_size', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('category_interest', sa.String(length=80), nullable=True))
    op.add_column('contacts', sa.Column('colour_preference', sa.String(length=80), nullable=True))
    op.add_column('contacts', sa.Column('budget_note', sa.String(length=160), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'budget_note')
    op.drop_column('contacts', 'colour_preference')
    op.drop_column('contacts', 'category_interest')
    op.drop_column('contacts', 'shoe_size')
    op.drop_column('contacts', 'city')
    # ### end Alembic commands ###
