"""persist llm failure reason

Revision ID: 6e8711ec3522
Revises: 6c08ef398d26
Create Date: 2026-09-09 03:33:29.197674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8711ec3522'
down_revision: Union[str, None] = '6c08ef398d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_logs', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_logs', 'error')
    # ### end Alembic commands ###
