"""Push subscriptions, the alert log, and what a job is worth.

Two features in one migration because both are purely additive and neither is
worth a container restart of its own.

The alerting half exists because the agent has always run headless. It answers
customers whether or not anybody has the dashboard open, which is the point -
but it also means that when a customer demands a manager at nine at night and
the agent correctly hands the conversation over, nobody finds out until the
morning. `push_subscriptions` holds the browsers that have agreed to be
interrupted; `notifications` holds what was raised, and doubles as the record
that stops the same situation being sent four times.

`deal_value` is deliberately not `budget`. Budget is free text holding
whatever the customer said; this is a number a person types in once they know,
and nothing generated by the model is ever written to it - a revenue figure on
a dashboard gets acted on, and an inferred one is a guess wearing a number's
clothes.

Revision ID: c9f3a61d8b42
Revises: b8e2f45c1a77
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

UUID = postgresql.UUID(as_uuid=True)

revision = "c9f3a61d8b42"
down_revision = "b8e2f45c1a77"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "push_subscriptions",
        sa.Column("id", UUID, primary_key=True),
        sa.Column(
            "organization_id",
            UUID,
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id", UUID, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=True
        ),
        # Unique on the endpoint alone, not per organization: the same browser
        # resubscribing must replace its row rather than add one, or a single
        # escalation arrives once for every time somebody reloaded the page.
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("p256dh", sa.String(255), nullable=False),
        sa.Column("auth", sa.String(255), nullable=False),
        sa.Column("label", sa.String(120), nullable=True),
        sa.Column("failures", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.UniqueConstraint("endpoint", name="uq_push_endpoint"),
    )
    op.create_index(
        "ix_push_subscriptions_organization_id", "push_subscriptions", ["organization_id"]
    )
    op.create_index("ix_push_subscriptions_user_id", "push_subscriptions", ["user_id"])

    op.create_table(
        "notifications",
        sa.Column("id", UUID, primary_key=True),
        sa.Column(
            "organization_id",
            UUID,
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "contact_id",
            UUID,
            sa.ForeignKey("crm_contacts.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("event", sa.String(32), nullable=False),
        sa.Column("title", sa.String(160), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("delivery", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )
    op.create_index("ix_notifications_organization_id", "notifications", ["organization_id"])
    op.create_index("ix_notifications_contact_id", "notifications", ["contact_id"])
    # The cool-off check: has this organization been told about this event
    # recently. It runs on the reply path, so it gets its own index.
    op.create_index(
        "ix_notifications_org_event_at",
        "notifications",
        ["organization_id", "event", "created_at"],
    )

    op.add_column(
        "organizations",
        sa.Column("notify_config", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
    )
    op.add_column("crm_contacts", sa.Column("deal_value", sa.Numeric(12, 2), nullable=True))


def downgrade() -> None:
    op.drop_column("crm_contacts", "deal_value")
    op.drop_column("organizations", "notify_config")

    op.drop_index("ix_notifications_org_event_at", table_name="notifications")
    op.drop_index("ix_notifications_contact_id", table_name="notifications")
    op.drop_index("ix_notifications_organization_id", table_name="notifications")
    op.drop_table("notifications")

    op.drop_index("ix_push_subscriptions_user_id", table_name="push_subscriptions")
    op.drop_index("ix_push_subscriptions_organization_id", table_name="push_subscriptions")
    op.drop_table("push_subscriptions")
