"""Capture the dashboard screenshots used in the client documentation.

Populates both tenants with real conversations first — an empty console makes a
poor screenshot, and a staged one would misrepresent the product — then shoots
the views the document refers to.

Every reply captured here was generated by the live pipeline.

    python scripts/make_doc_screenshots.py

Writes only to D:\\pingpulse\\docs\\images.
"""

from __future__ import annotations

import asyncio
import os
import pathlib
import sys
import time

import httpx
from playwright.async_api import async_playwright

BACKEND = "http://localhost:8000"
DASHBOARD = "http://localhost:3000"

OUT_DIR = pathlib.Path(r"D:\pingpulse\docs\images")
VIEWPORT = {"width": 1920, "height": 1080}

OPERATOR_EMAIL = os.environ.get("PINGPULSE_EMAIL", "demo@pingpulse.app")
OPERATOR_PASSWORD = os.environ.get("PINGPULSE_PASSWORD", "")

RETAIL_ORG, SAAS_ORG = "Aurora Retail", "Lumen Analytics"
RETAIL_NUMBER = "whatsapp:+14155238886"
SAAS_NUMBER = "whatsapp:+14155238887"

# A handful of shoppers per tenant, so the pipeline board and conversation list
# both have something real in them.
RETAIL_SCRIPT = [
    ("Maryam", "Do you have wireless earbuds? Send a photo and the price."),
    ("Omar", "Is cash on delivery available in Dubai?"),
    ("Layla", "I need a power bank for travel, what do you have?"),
]
SAAS_SCRIPT = [
    ("Daniel", "We're a 200 person company. What's the pricing for the enterprise plan?"),
    ("Priya", "Can we book a call to discuss enterprise pricing?"),
]


async def post(client, url, **kwargs):
    for attempt in range(3):
        try:
            response = await client.post(url, **kwargs)
            response.raise_for_status()
            return response
        except httpx.TransportError:
            if attempt == 2:
                raise
            await asyncio.sleep(1.0)


async def send(client, phone, to, text, name):
    await post(
        client, f"{BACKEND}/api/v1/whatsapp/webhook",
        data={
            "MessageSid": f"SM_doc_{abs(hash((phone, text))) % 10**10}",
            "From": f"whatsapp:{phone}",
            "To": to,
            "Body": text,
            "ProfileName": name,
            "NumMedia": "0",
        },
    )


async def switch(client, auth, orgs, name):
    target = next(m["organization"] for m in orgs if m["organization"]["name"] == name)
    await post(
        client, f"{BACKEND}/api/v1/organizations/switch", headers=auth,
        json={"organization_id": target["id"]},
    )
    return target


async def main() -> int:
    if not OPERATOR_PASSWORD:
        print("Set PINGPULSE_EMAIL and PINGPULSE_PASSWORD first.", file=sys.stderr)
        return 2

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    run = int(time.time()) % 100000

    async with httpx.AsyncClient(timeout=300) as api:
        token = (
            await api.post(
                f"{BACKEND}/api/v1/auth/login",
                json={"email": OPERATOR_EMAIL, "password": OPERATOR_PASSWORD},
            )
        ).json()["access_token"]
        auth = {"Authorization": f"Bearer {token}"}
        orgs = (await api.get(f"{BACKEND}/api/v1/organizations", headers=auth)).json()

        # Fresh boards in both tenants.
        for membership in orgs:
            await post(
                api, f"{BACKEND}/api/v1/organizations/switch", headers=auth,
                json={"organization_id": membership["organization"]["id"]},
            )
            for contact in (
                await api.get(f"{BACKEND}/api/v1/crm/contacts", headers=auth)
            ).json():
                await api.delete(
                    f"{BACKEND}/api/v1/crm/contacts/{contact['id']}", headers=auth
                )

        print("populating tenants (live pipeline) ...")
        for index, (name, text) in enumerate(RETAIL_SCRIPT):
            started = time.monotonic()
            await send(api, f"+9715{run}{index:02d}", RETAIL_NUMBER, text, name)
            print(f"  ({time.monotonic() - started:4.1f}s) retail  {name}")
        for index, (name, text) in enumerate(SAAS_SCRIPT):
            started = time.monotonic()
            await send(api, f"+1415{run}{index:02d}", SAAS_NUMBER, text, name)
            print(f"  ({time.monotonic() - started:4.1f}s) saas    {name}")

        await switch(api, auth, orgs, RETAIL_ORG)

        async with async_playwright() as p:
            browser = await p.chromium.launch(args=["--force-device-scale-factor=1"])
            context = await browser.new_context(viewport=VIEWPORT)
            page = await context.new_page()

            await page.goto(DASHBOARD, wait_until="networkidle")
            await page.wait_for_timeout(600)
            await page.fill('input[type="email"]', OPERATOR_EMAIL)
            await page.fill('input[type="password"]', OPERATOR_PASSWORD)
            await page.click('button[type="submit"]')
            await page.wait_for_timeout(3500)

            async def shoot(name: str) -> None:
                path = OUT_DIR / f"{name}.png"
                await page.screenshot(path=str(path))
                print(f"  shot {path.name} ({path.stat().st_size // 1024} KB)")

            # 1 — the multi-organisation dashboard, retail tenant active.
            await shoot("dashboard-retail")

            # 2 — a conversation with product cards attached.
            rows = page.locator("section:has-text('Conversations') button")
            if await rows.count():
                await rows.nth(0).click()
                await page.wait_for_timeout(2000)
            await shoot("conversation-media")

            # 3 — the same console on the other tenant, same login.
            await switch(api, auth, orgs, SAAS_ORG)
            switcher = page.locator("button, [role='button']").filter(has_text=RETAIL_ORG)
            if await switcher.count():
                await switcher.first.click()
                await page.wait_for_timeout(500)
                option = page.locator(f"text={SAAS_ORG}")
                if await option.count():
                    await option.first.click()
                else:
                    await page.reload(wait_until="networkidle")
            else:
                await page.reload(wait_until="networkidle")
            await page.wait_for_timeout(2500)
            await shoot("dashboard-saas")

            # 4 — a SaaS conversation, showing the booking reply and pipeline.
            rows = page.locator("section:has-text('Conversations') button")
            if await rows.count():
                await rows.nth(0).click()
                await page.wait_for_timeout(2000)
            await shoot("conversation-booking")

            await context.close()
            await browser.close()

    print(f"\n  images in {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
